org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Override in local.properties or ~/.gradle/gradle.properties if needed.
BACKEND_BASE_URL=http://10.0.2.2:8001/
GOOGLE_WEB_CLIENT_ID=637033140223-dlgjt4n029sk7ujaqso85u23nqof8qq4.apps.googleusercontent.com
